"""Slack-native cron store, matcher, scheduler tick, and !cron control phrases."""

from src.runners import claude_runner

from tests.helpers import (
    _FakeSay,
    _CONTROL_AGENT,
    _appmod,
    _HAVE_APP,
)


# ---------------------------------------------------------------------------
# CRON SCHEDULING (Slack-native). The store (crons.json, sibling of sessions.json)
# CRUD lives in src/store/crons.py (reached via the claude_runner facade); the
# 5-field cron matcher + the scheduler tick live in src/slack/scheduler.py
# (reached via the app facade). All time-based tests INJECT a datetime/clock (no
# sleep, no real wall-clock). Note: Claude Code has its own /schedule (cloud
# routines); this is the in-process Slack-native equivalent the user asked for.
# ---------------------------------------------------------------------------


def test_cron_store_add_list_remove(tmp_path):
    crons = str(tmp_path / "crons.json")
    assert claude_runner.list_crons(path=crons) == []
    e = claude_runner.add_cron(
        "0 9 * * *", "aristotle", "C1", "T1", "standup", cron_id="abc", path=crons
    )
    assert e["id"] == "abc"
    assert e["enabled"] is True
    got = claude_runner.list_crons(path=crons)
    assert len(got) == 1
    assert got[0]["schedule"] == "0 9 * * *"
    assert got[0]["agent"] == "aristotle"
    assert got[0]["prompt"] == "standup"
    # Removing a non-existent id is a no-op (False); the real id removes (True).
    assert claude_runner.remove_cron("nope", path=crons) is False
    assert claude_runner.remove_cron("abc", path=crons) is True
    assert claude_runner.list_crons(path=crons) == []


def test_cron_store_set_enabled_toggles(tmp_path):
    crons = str(tmp_path / "crons.json")
    claude_runner.add_cron(
        "* * * * *", "brunel", "C1", "T1", "ping", cron_id="x1", path=crons
    )
    assert claude_runner.set_cron_enabled("x1", False, path=crons) is True
    assert claude_runner.list_crons(path=crons)[0]["enabled"] is False
    assert claude_runner.set_cron_enabled("x1", True, path=crons) is True
    assert claude_runner.list_crons(path=crons)[0]["enabled"] is True
    # Unknown id -> False, no crash.
    assert claude_runner.set_cron_enabled("nope", True, path=crons) is False


def test_cron_store_id_autogenerated_and_unique(tmp_path):
    crons = str(tmp_path / "crons.json")
    a = claude_runner.add_cron("* * * * *", "g", "C", "T", "p", path=crons)
    b = claude_runner.add_cron("* * * * *", "g", "C", "T", "p", path=crons)
    assert a["id"] and b["id"] and a["id"] != b["id"]


def test_cron_store_path_from_sessions_env(monkeypatch, tmp_path):
    # crons.json is a sibling of the sessions path, so SESSIONS_PATH redirects it.
    monkeypatch.setenv("SESSIONS_PATH", str(tmp_path / "sessions.json"))
    assert claude_runner._crons_path() == str(tmp_path / "crons.json")


def test_cron_store_corrupt_file_yields_empty(tmp_path):
    crons = tmp_path / "crons.json"
    crons.write_text("{not json", encoding="utf-8")
    assert claude_runner.list_crons(path=str(crons)) == []


def test_cron_matches_wildcard_every_minute():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    assert _appmod.cron_matches("* * * * *", datetime(2026, 6, 24, 9, 0))
    assert _appmod.cron_matches("* * * * *", datetime(2026, 1, 1, 0, 0))


def test_cron_matches_specific_minute_hour():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    expr = "30 9 * * *"  # 09:30 daily
    assert _appmod.cron_matches(expr, datetime(2026, 6, 24, 9, 30))
    assert not _appmod.cron_matches(expr, datetime(2026, 6, 24, 9, 31))
    assert not _appmod.cron_matches(expr, datetime(2026, 6, 24, 10, 30))
    assert not _appmod.cron_matches(expr, datetime(2026, 6, 24, 8, 30))


def test_cron_matches_lists_ranges_and_steps():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    # minute list
    assert _appmod.cron_matches("0,15,30 * * * *", datetime(2026, 6, 24, 9, 15))
    assert not _appmod.cron_matches("0,15,30 * * * *", datetime(2026, 6, 24, 9, 16))
    # hour range
    assert _appmod.cron_matches("0 9-17 * * *", datetime(2026, 6, 24, 12, 0))
    assert not _appmod.cron_matches("0 9-17 * * *", datetime(2026, 6, 24, 18, 0))
    # step every 15 minutes
    assert _appmod.cron_matches("*/15 * * * *", datetime(2026, 6, 24, 9, 45))
    assert not _appmod.cron_matches("*/15 * * * *", datetime(2026, 6, 24, 9, 46))
    # range with step on hours
    assert _appmod.cron_matches("0 0-12/6 * * *", datetime(2026, 6, 24, 6, 0))
    assert not _appmod.cron_matches("0 0-12/6 * * *", datetime(2026, 6, 24, 7, 0))


def test_cron_matches_day_of_week():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    # 2026-06-22 is a Monday (dow 1; cron 0=Sun..6=Sat). 2026-06-21 is Sunday (0).
    expr = "0 9 * * 1"  # Mondays at 09:00
    assert _appmod.cron_matches(expr, datetime(2026, 6, 22, 9, 0))  # Monday
    assert not _appmod.cron_matches(expr, datetime(2026, 6, 21, 9, 0))  # Sunday
    # Sunday matches both 0 and 7.
    assert _appmod.cron_matches("0 9 * * 0", datetime(2026, 6, 21, 9, 0))
    assert _appmod.cron_matches("0 9 * * 7", datetime(2026, 6, 21, 9, 0))


def test_cron_matches_month_and_dom():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    expr = "0 0 1 1 *"  # midnight on Jan 1
    assert _appmod.cron_matches(expr, datetime(2026, 1, 1, 0, 0))
    assert not _appmod.cron_matches(expr, datetime(2026, 2, 1, 0, 0))
    assert not _appmod.cron_matches(expr, datetime(2026, 1, 2, 0, 0))


def test_cron_matches_invalid_expr_never_matches():
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    # Wrong field count / garbage -> safe False, never a crash.
    assert not _appmod.cron_matches("not a cron", datetime(2026, 6, 24, 9, 0))
    assert not _appmod.cron_matches("* * *", datetime(2026, 6, 24, 9, 0))
    assert not _appmod.cron_matches("99 * * * *", datetime(2026, 6, 24, 9, 0))


# --- control phrase: !cron add/list/remove/off/on ---


def test_control_phrase_cron_add_then_list(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    say = _FakeSay()
    handled = _appmod._handle_control_phrase(
        _CONTROL_AGENT,
        '!cron add "0 9 * * *" run the standup',
        "T1",
        say,
        channel_id="C1",
    )
    assert handled is True
    stored = claude_runner.list_crons(path=crons)
    assert len(stored) == 1
    assert stored[0]["schedule"] == "0 9 * * *"
    assert stored[0]["prompt"] == "run the standup"
    assert stored[0]["agent"] == "aristotle"
    assert stored[0]["channel"] == "C1"
    assert stored[0]["thread_ts"] == "T1"
    # The confirmation echoes the new id + schedule.
    assert stored[0]["id"] in say.posts[0]["text"]

    # !cron list shows it.
    say2 = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron list", "T1", say2)
    assert "0 9 * * *" in say2.posts[0]["text"]
    assert stored[0]["id"] in say2.posts[0]["text"]


def test_control_phrase_cron_list_empty(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    say = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron list", "T1", say)
    assert "no" in say.posts[0]["text"].lower()  # "no crons" / "none"


def test_control_phrase_cron_add_bad_usage(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    say = _FakeSay()
    # Missing the quoted schedule -> usage line, nothing stored.
    _appmod._handle_control_phrase(
        _CONTROL_AGENT, "!cron add do something", "T1", say, channel_id="C1"
    )
    assert "usage" in say.posts[0]["text"].lower()
    assert claude_runner.list_crons(path=crons) == []


def test_control_phrase_cron_remove(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    claude_runner.add_cron(
        "0 9 * * *", "aristotle", "C1", "T1", "p", cron_id="rm1", path=crons
    )
    say = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron remove rm1", "T1", say)
    assert claude_runner.list_crons(path=crons) == []
    assert "rm1" in say.posts[0]["text"]
    # Removing an unknown id reports not-found, no crash.
    say2 = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron remove nope", "T1", say2)
    assert "not" in say2.posts[0]["text"].lower()


def test_control_phrase_cron_off_then_on(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    claude_runner.add_cron(
        "0 9 * * *", "aristotle", "C1", "T1", "p", cron_id="t1", path=crons
    )
    say = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron off t1", "T1", say)
    assert claude_runner.list_crons(path=crons)[0]["enabled"] is False
    say2 = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron on t1", "T1", say2)
    assert claude_runner.list_crons(path=crons)[0]["enabled"] is True


def test_control_phrase_cron_unknown_subcommand(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    say = _FakeSay()
    _appmod._handle_control_phrase(_CONTROL_AGENT, "!cron frobnicate", "T1", say)
    assert "usage" in say.posts[0]["text"].lower()


# --- the fire path: a matching cron synthesizes a run via _run_and_update ---


def test_scheduler_tick_fires_matching_cron_via_run_seam(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    crons = str(tmp_path / "crons.json")
    monkeypatch.setattr(claude_runner, "_crons_path", lambda: crons)
    claude_runner.add_cron(
        "30 9 * * *", "aristotle", "C9", "T9", "do it", cron_id="f1", path=crons
    )
    # A disabled cron at the same minute must NOT fire.
    claude_runner.add_cron(
        "30 9 * * *", "aristotle", "C9", "T9", "skip", cron_id="off1", path=crons
    )
    claude_runner.set_cron_enabled("off1", False, path=crons)
    # A non-matching cron must NOT fire.
    claude_runner.add_cron(
        "0 0 * * *", "aristotle", "C9", "T9", "later", cron_id="nomatch", path=crons
    )

    import threading as _threading

    fired = []
    fired_evt = _threading.Event()

    def _fake_fire(entry, live):
        fired.append(entry["id"])
        fired_evt.set()

    monkeypatch.setattr(_appmod, "_fire_cron", _fake_fire)

    # The tick fires each match on its OWN daemon thread (so one long cron run
    # can't block the loop); wait on the event before asserting the fire landed.
    n = _appmod._scheduler_tick({}, now=datetime(2026, 6, 24, 9, 30))
    assert n == 1
    assert fired_evt.wait(timeout=5)
    assert fired == ["f1"]
    # A non-matching minute fires nothing.
    fired.clear()
    n2 = _appmod._scheduler_tick({}, now=datetime(2026, 6, 24, 9, 31))
    assert n2 == 0
    assert fired == []


def test_fire_cron_runs_agent_in_target_thread(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    # _fire_cron resolves the agent from the registry, posts a placeholder into the
    # cron's channel/thread, and synthesizes a run via _run_and_update with the
    # cron's agent + prompt + thread. We stub _run_and_update and the live client.
    entry = {
        "id": "f1",
        "schedule": "* * * * *",
        "agent": "aristotle",
        "channel": "C9",
        # A REAL ts-shaped key: the placeholder posts into that thread (a
        # flat-DM channel-id key posts flat; see test_dm.py).
        "thread_ts": "9000000000.000900",
        "prompt": "do the thing",
        "enabled": True,
    }
    captured = {}

    class _Client:
        def chat_postMessage(self, channel=None, thread_ts=None, text=None):
            captured["placeholder"] = {
                "channel": channel,
                "thread_ts": thread_ts,
                "text": text,
            }
            return {"ts": "ph-ts"}

    class _App:
        client = _Client()

    class _Handler:
        app = _App()

    live = {"aristotle": {"handler": _Handler()}}

    def _fake_run_and_update(client, channel, placeholder_ts, agent, prompt, thread_ts):
        captured["run"] = {
            "channel": channel,
            "placeholder_ts": placeholder_ts,
            "agent_name": agent["name"],
            "prompt": prompt,
            "thread_ts": thread_ts,
        }

    monkeypatch.setattr(_appmod, "_run_and_update", _fake_run_and_update)
    _appmod._fire_cron(entry, live)

    assert captured["placeholder"]["channel"] == "C9"
    assert captured["placeholder"]["thread_ts"] == "9000000000.000900"
    run = captured["run"]
    assert run["channel"] == "C9"
    assert run["thread_ts"] == "9000000000.000900"
    assert run["placeholder_ts"] == "ph-ts"
    assert run["agent_name"] == "aristotle"
    assert run["prompt"] == "do the thing"


def test_fire_cron_unknown_agent_is_noop(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    entry = {
        "id": "f1",
        "agent": "ghost",  # not in REGISTRY / not live
        "channel": "C9",
        "thread_ts": "T9",
        "prompt": "x",
        "enabled": True,
    }
    called = []
    monkeypatch.setattr(_appmod, "_run_and_update", lambda *a, **k: called.append(True))
    # No live handler for "ghost" -> _fire_cron must not raise and must not run.
    _appmod._fire_cron(entry, {})
    assert called == []


def test_scheduler_loop_ticks_once_with_injected_clock(monkeypatch, tmp_path):
    if not _HAVE_APP:
        return
    assert _appmod is not None
    from datetime import datetime

    # _scheduler_loop(live, _once=True) runs a single tick using the injected now()
    # and never sleeps in the test (the sleep seam is stubbed / the once path skips).
    ticks = []
    monkeypatch.setattr(_appmod, "_scheduler_tick", lambda live, now: ticks.append(now))
    fixed = datetime(2026, 6, 24, 9, 30)
    _appmod._scheduler_loop({}, now=lambda: fixed, _once=True)
    assert ticks == [fixed]
